### ISSUE TITLE
urllib3.exceptions.NewConnectionError in macOS check

### ISSUE THREAD

**Issue by nick-youngblut** [conda-forge/r-narray-feedstock#1]
@bgruening any idea what's causing the `urllib3.exceptions.NewConnectionError` in the macOS build? I don't see anything weird in the recipe. Maybe it's the `.travis.yml` file?

**Comment by jdblischak** [comment]
@nick-youngblut Did you try restarting the Travis build? The timeout may have been spurious.

**Comment by bgruening** [comment]
Restarted and fixed. Thanks both, as usual  you rock :)
